workflows:
  ios-cordova-signed:
    name: Build iOS Cordova (Assinatura Automática)

    environment:
      node: 14.20.0
      xcode: 16.1
      vars:
        CORDOVA_IOS_VERSION: "6.2.0"

    scripts:
      - name: Instalar Cordova e dependências
        script: |
          npm install -g npm@6.14.17
          npm install -g cordova@11.1.0
          npm install

      - name: Remover plataforma Android (evitar conflitos)
        script: |
          cordova platform remove android || true

      - name: Preparar plataforma iOS
        script: |
          cordova platform remove ios || true
          cordova platform add ios@${CORDOVA_IOS_VERSION}

      - name: Forçar conversão do fix_signing.sh (CRLF → LF)
        script: |
          echo "Convertendo fix_signing.sh para LF (método TR + SED)..."

          # Remove CRLF
          tr -d '\r' < fix_signing.sh > fix_signing.tmp
          mv fix_signing.tmp fix_signing.sh

          # Corrige shebang
          sed -i '' '1 s|.*|#!/usr/bin/env bash|' fix_signing.sh

          chmod +x fix_signing.sh
          echo "Arquivo convertido corretamente!"

      - name: DEBUG antes do patch
        script: |
          echo "===== ANTES DO PATCH ====="
          PROJECT_FILE="platforms/ios/Saudi-AcomMed.xcodeproj/project.pbxproj"
          grep -R "CODE_SIGN_IDENTITY" -n $PROJECT_FILE || echo "Nenhum CODE_SIGN_IDENTITY encontrado"
          grep -R "DEVELOPMENT_TEAM" -n $PROJECT_FILE || echo "Nenhum DEVELOPMENT_TEAM encontrado"

      - name: Aplicar patch de assinatura
        script: |
          ./fix_signing.sh

      - name: DEBUG depois do patch
        script: |
          echo "===== DEPOIS DO PATCH ====="
          PROJECT_FILE="platforms/ios/Saudi-AcomMed.xcodeproj/project.pbxproj"
          grep -R "CODE_SIGN_IDENTITY" -n $PROJECT_FILE || echo "Nenhum CODE_SIGN_IDENTITY encontrado"
          grep -R "DEVELOPMENT_TEAM" -n $PROJECT_FILE || echo "Nenhum DEVELOPMENT_TEAM encontrado"

      - name: Build iOS com assinatura automática
        script: |
          cordova build ios --release --device --buildConfig=build.json -- --allowProvisioningUpdates

    artifacts:
      - platforms/ios/build/device/*.ipa
      - platforms/ios/build/**/*.xcarchive
