workflows:
  ios-cordova-debug:
    name: iOS Cordova DEBUG – Manual Signing

    environment:
      node: 14.20.0
      xcode: 16.1

    scripts:
      - name: Instalar dependências
        script: |
          npm install -g cordova@11.1.0
          npm install

      - name: Preparar plataforma iOS
        script: |
          cordova platform remove ios || true
          cordova platform add ios@6.2.0

      - name: Corrigir fix_signing.sh
        script: |
          tr -d '\r' < fix_signing.sh > fix_signing.tmp
          mv fix_signing.tmp fix_signing.sh
          chmod +x fix_signing.sh

      - name: Aplicar assinatura manual
        script: |
          ./fix_signing.sh

      - name: Debug assinatura
        script: |
          echo "==== CODE_SIGN_STYLE ===="
          grep -R "CODE_SIGN_STYLE" -n platforms/ios/Saudi-AcomMed.xcodeproj/project.pbxproj || true

          echo "==== PROVISIONING_PROFILE_SPECIFIER ===="
          grep -R "PROVISIONING_PROFILE_SPECIFIER" -n platforms/ios/Saudi-AcomMed.xcodeproj/project.pbxproj || true

          echo "==== CODE_SIGN_IDENTITY ===="
          grep -R "CODE_SIGN_IDENTITY" -n platforms/ios/Saudi-AcomMed.xcodeproj/project.pbxproj || true

      - name: Build iOS DEBUG
        script: |
          cordova build ios --debug --device

    artifacts:
      - platforms/ios/build/device/**/*.app
