workflows:
  ios-cordova-debug:
    name: iOS Cordova Debug (Provisioning Manual)

    environment:
      node: 14.20.0
      xcode: 16.1

    scripts:
      # -------------------------------
      # 1. Dependências
      # -------------------------------
      - name: Instalar Cordova e dependências
        script: |
          npm install -g npm@6.14.17
          npm install -g cordova@11.1.0
          npm install

      # -------------------------------
      # 2. Limpeza de plataformas
      # -------------------------------
      - name: Remover plataformas antigas
        script: |
          cordova platform remove ios || true
          cordova platform remove android || true

      # -------------------------------
      # 3. Adicionar iOS
      # -------------------------------
      - name: Adicionar plataforma iOS
        script: |
          cordova platform add ios@6.2.0

      # -------------------------------
      # 4. Corrigir CRLF + Permissões
      # -------------------------------
      - name: Normalizar fix_signing.sh
        script: |
          tr -d '\r' < fix_signing.sh > fix_signing.tmp
          mv fix_signing.tmp fix_signing.sh
          sed -i '' '1s|.*|#!/usr/bin/env bash|' fix_signing.sh
          chmod +x fix_signing.sh

      # -------------------------------
      # 5. Aplicar patch de assinatura
      # -------------------------------
      - name: Aplicar patch de assinatura
        script: |
          ./fix_signing.sh

      # -------------------------------
      # 6. Validação do ambiente iOS
      # -------------------------------
      - name: Validar certificados e provisioning
        script: |
          echo "== CERTIFICADOS =="
          security find-identity -v -p codesigning

          echo "== PROFILES INSTALADOS =="
          ls -l ~/Library/MobileDevice/Provisioning\ Profiles

      # -------------------------------
      # 7. Build DEBUG com profile DEV
      # -------------------------------
      - name: Build iOS DEBUG
        script: |
          cordova build i
