workflows:
  ios-simulator-debug:
    name: iOS Simulator Debug (No Signing)
    max_build_duration: 60

    environment:
      xcode: 16.1
      node: 18

    scripts:
      - name: Install dependencies
        script: |
          npm install -g cordova@11
          npm install --legacy-peer-deps

      - name: Prepare iOS platform
        script: |
          cordova platform remove ios || true
          cordova platform add ios@6.2.0

      - name: Build iOS Simulator (Debug)
        script: |
          cordova build ios --debug --emulator

    artifacts:
      - platforms/ios/build/emulator/**/*.app
